parameters:
  robot_name:
    default: "Unnamed Deployment Robot"
    type: string
  robot_email:
    default: "no@such.email"
    type: string
steps:
  - run: git config user.email "<< parameters.robot_email >>"
  - run: git config user.name "<< parameters.robot_name >>"
  - run: git config --global push.default matching
